[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["pytreenet"]

[project]
name = "pytreenet"
version = "1.0.0"
description = "Tree tensor network library for quantum simulations"
readme = "README.md"
authors = [{ name = "Richard M. Milbradt", email = "r.milbradt@tum.de" },
            { name = "Qunsheng Huang"}]
maintainer = [{ name = "Richard M. Milbradt", email = "r.milbradt@tum.de" }]
license = { text = "European Union Public License, v1.1" }
requires-python = ">=3.8.10"
dependencies = [
    "numpy >= 1.24.3",
    "scipy >= 1.10.1",
    "tqdm >= 4.65.0",
    "h5py >= 3.10.0",
]

[project.optional-dependencies]
notebook = ["ipykernel >= 6.24.0", "matplotlib==3.7.2"]

[project.urls]
Repository = "https://github.com/Drachier/PyTreeNet"